### ISSUE TITLE
Potential bug in parsing of element section

### ISSUE THREAD

**Issue by danleh** [acieroid/wassail#2]
Hi!
There might a bug in the parsing of element sections of the Wasm text format. Specifically, it seems the parser cannot deal with the (optional) `func` keyword before the list of function elements. E.g., the test file https://github.com/acieroid/wassail/blob/master/test/call_indirect-with_imported_element.wat has no `func`, but if added before `$bar` on line 10, wassail errors out. Is this intended?
Best,
Daniel

**Comment by michelledaviest** [comment]
This is the error message we get: 
```
wassail callgraph call_indirect-with_imported_element.wat call_ind.dot 
Uncaught exception:
  
  (Failure
   "Error: call_indirect-with_imported_element.wat:10.23-10.27: syntax error: unexpected token")

Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
Called from Base__Exn.protectx in file "src/exn.ml", line 80, characters 8-11
Re-raised at Base__Exn.raise_with_original_backtrace in file "src/exn.ml" (inlined), line 60, characters 2-48
Called from Base__Exn.protectx in file "src/exn.ml", line 87, characters 13-49
Called from Dune__exe__Callgraph.callgraph.(fun) in file "callgraph.ml", line 11, characters 23-50
Called from Core__Command.For_unix.dispatch.parse_group.resolve in file "core/src/command.ml", line 2761, characters 12-352
Called from Core__Command.For_unix.run.(fun) in file "core/src/command.ml", line 2871, characters 8-270
Called from Base__Exn.handle_uncaught_aux in file "src/exn.ml", line 127, characters 6-10
```

**Comment by acieroid** [comment]
Hi and thanks for the report! (Sorry for the delay, it seems that I'm not getting github notifications for new issues.)
This is indeed a current limitation. We use the specification's interpreter for parsing the .wat file, which seems to have this limitation in its version 1.1.1.
I plan to update wassail to rely on the latest version of the spec's implementation, but this requires some not-so-trivial changes. I'll keep you updated once this is fixed.

In the meantime, one trick that could solve this is to convert the `.wat` into a `.wasm` file (e.g., with `wat2wasm`), which should be succesfully loaded by wassail.

**Comment by danleh** [comment]
Thanks for the answer and no worries about the delay! The workaround would be fine for us, just wanted to confirm its not the intended behavior by wassail.

**Comment by acieroid** [comment]
I upgraded the wasm dependency to version 2.0.0, and this is now fixed!
